"""Alembic environment -- synchronous, matching the application engine.

The database URL comes from ``app.core.config.get_settings()``, never from
``alembic.ini``: one source of truth, and no credentials committed to git.
"""

from __future__ import annotations

from logging.config import fileConfig
from typing import Any, Literal

from alembic import context
from sqlalchemy import Connection, create_engine, pool

from app.core.config import get_settings

try:
    from app.models.base import Base
except ImportError as exc:  # pragma: no cover - guides the models track
    message = (
        "Alembic could not import `app.models.base:Base`.\n"
        "\n"
        "The migrations environment needs the SQLAlchemy declarative Base so that\n"
        "autogenerate can diff the models against the database.\n"
        "\n"
        "Fix: create `apps/api/app/models/base.py` defining\n"
        "    class Base(DeclarativeBase): ...\n"
        "and import every model module so its tables are registered on\n"
        "`Base.metadata` before running Alembic.\n"
        f"\nUnderlying import error: {exc}"
    )
    raise RuntimeError(message) from exc

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

VERSION_TABLE = "alembic_version"


def get_url() -> str:
    """Return the database URL from application settings."""
    return get_settings().database_url


def render_item(
    type_: str,
    obj: Any,
    autogen_context: Any,
) -> str | Literal[False]:
    """Render pgvector column types with the import autogenerate would omit.

    Without this, an autogenerated migration emits a bare ``Vector(dim=1536)``
    and fails at import time because ``pgvector.sqlalchemy`` was never imported.
    Returning ``False`` defers every other type to Alembic's default rendering.
    """
    if type_ == "type" and obj.__class__.__module__.startswith("pgvector"):
        autogen_context.imports.add("import pgvector.sqlalchemy")
        class_name = obj.__class__.__name__
        dim = getattr(obj, "dim", None)
        if dim is None:
            return f"pgvector.sqlalchemy.{class_name}()"
        return f"pgvector.sqlalchemy.{class_name}(dim={dim!r})"
    return False


def _configure(connection: Connection | None, url: str | None) -> None:
    """Apply the options shared by the offline and online paths."""
    context.configure(
        connection=connection,
        url=url,
        target_metadata=target_metadata,
        version_table=VERSION_TABLE,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        render_item=render_item,
        include_schemas=False,
        dialect_opts={"paramstyle": "named"},
        literal_binds=connection is None,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to a database."""
    _configure(connection=None, url=get_url())
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect with a synchronous engine and run migrations in a transaction."""
    connectable = create_engine(get_url(), poolclass=pool.NullPool)
    try:
        with connectable.connect() as connection:
            _configure(connection=connection, url=None)
            with context.begin_transaction():
                context.run_migrations()
    finally:
        connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
