"""section 4a routing trace fields and brief workflow states

Revision ID: aeccc5357b7d
Revises: c5434a714f7a
Create Date: 2026-09-07 17:02:51.138464+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeccc5357b7d"
down_revision: str | None = "c5434a714f7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_traces",
        sa.Column(
            "model_tier",
            sa.String(length=16),
            nullable=True,
            comment="BUILD_BIBLE section 4a capability tier: 'fast' for classify/score, 'strong' for briefs and meeting prep. Secondary to sensitivity - the band decides whether a model may be asked at all, the tier only decides which one.",
        ),
    )
    op.add_column(
        "ai_traces",
        sa.Column(
            "route_badge",
            sa.String(length=160),
            nullable=False,
            # Backfills the traces that already exist. They were routed before the badge
            # was recorded, and an empty string says exactly that - which is honest, where
            # inventing a badge for a decision we did not capture would not be.
            server_default="",
            comment="The section 4a trace-drawer badge, e.g. 'PUBLIC · external · claude-sonnet-5 · strong'. Stored rendered rather than assembled by the UI: 4a requires it to be legible to a non-technical Ambassador, and a drawer that re-derives it can drift from what the Gateway actually decided.",
        ),
    )
    # -- Brief workflow states (hand-written: autogenerate never ALTERs an enum) ------
    #
    # DRAFT -> IN_REVIEW -> APPROVED -> PUBLISHED. The type already exists with two of the
    # four values, so the two new ones are appended rather than the type recreated -
    # recreating it would mean dropping the column that uses it.
    #
    # ADD VALUE is allowed inside a transaction on PG12+, but the new label cannot be USED
    # in the same transaction. This migration only declares them; the seed and the service
    # use them afterwards, so that restriction is not a problem here.
    for label in ("IN_REVIEW", "APPROVED"):
        op.execute(f"ALTER TYPE brief_status ADD VALUE IF NOT EXISTS '{label}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision.

    The two brief_status labels are NOT removed. Postgres has no DROP VALUE, and the only
    way back is to recreate the type and rewrite every column using it - which would be a
    far more destructive operation than the one being undone. Leaving two unused labels in
    an enum is harmless; the Python enum is the authority on which are legal.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_traces", "route_badge")
    op.drop_column("ai_traces", "model_tier")
    # ### end Alembic commands ###
