"""per purpose gateway budget on ai traces

Revision ID: 23ac25a31005
Revises: aeccc5357b7d
Create Date: 2026-09-07 17:55:47.425497+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23ac25a31005"
down_revision: str | None = "aeccc5357b7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision.

    ONE column. Everything else autogenerate proposed here was noise it cannot see past:
    it does not know about the hand-written opclass indexes from the W2.1 migration
    (HNSW/vector_cosine_ops, GIN/to_tsvector, GIN/gin_trgm_ops), so it offered to drop them
    and recreate them on downgrade -- which, applied as generated, simply DELETES them and
    silently turns every retrieval query into a sequential scan. Removed, along with the
    server_default churn on columns this revision does not touch.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_traces",
        sa.Column(
            "budget_seconds",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
            comment="Wall-clock budget this call was given, in seconds. PER PURPOSE, not global: a purpose returning a score gets ~4s, one generating prose gets 25s. Recorded because 'it fell back' means something different at 4s than at 25s, and a reader cannot tell which without knowing what the call was actually allowed.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_traces", "budget_seconds")
    # ### end Alembic commands ###
