"""meeting followups and structured pre read

Revision ID: bd6ba29a9bde
Revises: 23ac25a31005
Create Date: 2026-09-15 08:08:00.000000+00:00

HAND-WRITTEN, not autogenerated. Autogenerate against this schema proposes dropping the
W2.1 opclass indexes it cannot see (HNSW/vector_cosine_ops, GIN/to_tsvector,
GIN/gin_trgm_ops -- see ``docs/W2_STATUS.md`` section 4 item 2 and the 23ac25a31005
docstring), and it cannot express a data copy, a partial unique index predicate it did not
write, or a trigger at all. Every statement below is deliberate.

WHAT THIS REVISION DOES (W3.2, winning moment #2)
-------------------------------------------------
1. ``meetings.pre_read_result`` (JSONB, NULL): the structured ``MeetingPrepResult`` the
   Gateway produced, validated before write, so the meeting page can render talking points
   with resolvable citations instead of a prose blob. "Not prepared" is SQL NULL, never the
   JSON literal ``'null'``: the model binds ``None`` as NULL (``none_as_null=True``), and an
   idempotent UPDATE turns any JSON ``'null'`` already stored into SQL NULL.
2. ``meeting_followups``: follow-ups move off ``meetings`` into their own table, one-to-many.
   With eight ``followup_*`` columns on ``meetings`` a meeting could hold one follow-up ever,
   so re-drafting after a discard would overwrite -- delete -- the discarded draft, which the
   Q-05 ruling forbids ("NEVER delete a drafted diplomatic communication").
3. ``uq_meeting_followups_one_live_per_meeting``: a partial unique index, at most one
   follow-up per meeting in ``DRAFTED``/``OFFICER_REVIEW``/``APPROVED``.
4. A data copy of every existing ``meetings.followup_*`` follow-up into the new table.
5. The eight old columns, their two CHECKs, two foreign keys and index are dropped.
6. Three triggers: no DELETE, no TRUNCATE, and an UPDATE guard (terminal rows immutable,
   provenance immutable, status changes limited to the ``FOLLOWUP_TRANSITIONS`` pairs,
   content changed only on ``DRAFTED`` to ``DRAFTED``, approval set only by
   ``OFFICER_REVIEW`` to ``APPROVED`` and cleared only by a return to ``DRAFTED``), plus
   table privileges.

The CHECK constraints are the model's (``app/models/meetings.py::MeetingFollowup``),
written out here with their rendered ``ck_meeting_followups_*`` names. What they and the
guard add up to -- and what they cannot know, such as whether a named approver held the
approve permission, or whether a row INSERTed as ``SENT`` was ever approved -- is written
out in that model's docstring and in ``docs/workflows.md`` section 2.

THE DATA COPY, AND WHAT IT REFUSES TO GUESS
-------------------------------------------
Each follow-up is copied as recorded, never rewritten:

* ``body`` is the old ``followup_draft`` **verbatim**. A drafted diplomatic communication is
  not edited by a migration, not even to strip a status banner out of it.
* ``subject`` is the text of the first line beginning ``Subject:`` in the draft, or the
  meeting title when there is none (both bounded at 300).
* ``recipients`` is ``[organisation name]`` when the meeting has a counterpart organisation,
  else ``["Meeting participants"]`` -- labels, never addresses.
* ``drafted_by_user_id`` is the meeting owner, and ``submitted_by``/``sent_by``/
  ``discarded_by`` are the owner where those acts happened: the old schema recorded no actor
  for them, and the owner is the only officer the row names. A follow-up on a meeting with
  **no owner** stops the migration with a RuntimeError -- an author is never invented.
* ``drafted_at`` is the earliest recorded act on the follow-up (submission, approval,
  dispatch, discard), falling back to the meeting's ``created_at``. For every submitted
  follow-up that is the submission time; for one discarded straight from draft it is the
  discard time rather than a creation time that would post-date its own discard.
* A discarded follow-up gets the reason "Recorded before follow-ups had their own table; the
  reason was not captured at the time." -- true, and the table requires a reason.
* Rows the new constraints would refuse (an approver equal to the owner, ``SENT`` with no
  approval time, ``APPROVED`` or ``SENT`` with no submission time, an approval on a row
  still ``DRAFTED`` or ``OFFICER_REVIEW``, an approval recorded before its submission or a
  dispatch before its approval, ``DISCARDED`` with no discard time, and so on) stop the
  migration with a RuntimeError naming the meeting, rather than failing on an anonymous
  CHECK or being silently "repaired". The copy is an INSERT of history, not an approval
  act: the UPDATE guard below does not see it, and it invents no approval the old row did
  not record.

DOWNGRADE, AND WHAT IT LOSES
----------------------------
The old schema holds one follow-up per meeting, so downgrade copies back the MOST RECENT
follow-up per meeting (by ``drafted_at``). **Older follow-ups -- every discarded draft that
was later superseded -- are lost on downgrade**, as are ``recipients``, the actor columns
and ``discard_reason``, which the old columns cannot hold. The subject survives: when the
body carries no ``Subject:`` line, ``Subject: <subject>`` is prepended to the draft text, the
only text column the old schema has. ``pre_read_result`` is dropped. The ``followup_status``
enum type is never dropped: it predates this revision and the old column reuses it.
"""

from __future__ import annotations

import json
import re
import uuid
from collections.abc import Sequence
from datetime import datetime
from typing import Any, Final

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from ulid import ULID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6ba29a9bde"
down_revision: str | None = "23ac25a31005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE: Final[str] = "meeting_followups"
LIVE_INDEX: Final[str] = "uq_meeting_followups_one_live_per_meeting"

REJECT_DELETE_FUNCTION: Final[str] = "naddp_reject_followup_delete"
GUARD_UPDATE_FUNCTION: Final[str] = "naddp_guard_followup_update"
NO_DELETE_TRIGGER: Final[str] = "trg_meeting_followups_no_delete"
NO_TRUNCATE_TRIGGER: Final[str] = "trg_meeting_followups_no_truncate"
GUARD_UPDATE_TRIGGER: Final[str] = "trg_meeting_followups_guard_update"

#: Stored on a follow-up that was DISCARDED under the old schema, which kept no reason.
MIGRATED_DISCARD_REASON: Final[str] = (
    "Recorded before follow-ups had their own table; the reason was not captured at the time."
)

#: Recipient label for a follow-up on a meeting with no counterpart organisation.
MIGRATED_RECIPIENT_FALLBACK: Final[str] = "Meeting participants"

SUBJECT_MAX: Final[int] = 300

#: The first line of a draft that begins ``Subject:``, and the text after it.
_SUBJECT_LINE: Final[re.Pattern[str]] = re.compile(r"^Subject:[ \t]*(?P<subject>.*?)\s*$", re.M)

#: The eight columns this revision moves off ``meetings``.
OLD_COLUMNS: Final[tuple[str, ...]] = (
    "followup_status",
    "followup_draft",
    "followup_trace_id",
    "followup_submitted_at",
    "followup_approved_by_user_id",
    "followup_approved_at",
    "followup_sent_at",
    "followup_discarded_at",
)

FOLLOWUP_STATUS_TYPE: Final[postgresql.ENUM] = postgresql.ENUM(
    "DRAFTED",
    "OFFICER_REVIEW",
    "APPROVED",
    "SENT",
    "DISCARDED",
    name="followup_status",
    create_type=False,
)
CLASSIFICATION_TYPE: Final[postgresql.ENUM] = postgresql.ENUM(
    "PUBLIC",
    "MISSION_INTERNAL",
    "CONFIDENTIAL",
    "CONSULAR_SENSITIVE",
    name="classification",
    create_type=False,
)

_SELECT_OLD_FOLLOWUPS: Final[str] = """
    SELECT m.id AS meeting_id,
           m.title,
           m.owner_user_id,
           o.name AS organisation_name,
           CAST(m.classification AS text) AS classification,
           m.created_at,
           CAST(m.followup_status AS text) AS status,
           m.followup_draft,
           m.followup_trace_id,
           m.followup_submitted_at,
           m.followup_approved_by_user_id,
           m.followup_approved_at,
           m.followup_sent_at,
           m.followup_discarded_at
      FROM meetings AS m
      LEFT JOIN organisations AS o ON o.id = m.organisation_id
     WHERE m.followup_status IS NOT NULL
     ORDER BY m.id
"""

_INSERT_FOLLOWUP: Final[str] = """
    INSERT INTO meeting_followups (
        id, meeting_id, status, subject, recipients, body, trace_id, supersedes_followup_id,
        drafted_by_user_id, drafted_at, submitted_by_user_id, submitted_at,
        approved_by_user_id, approved_at, sent_by_user_id, sent_at,
        discarded_by_user_id, discarded_at, discard_reason, classification
    ) VALUES (
        :id, :meeting_id, CAST(:status AS followup_status), :subject,
        CAST(:recipients AS jsonb), :body, :trace_id, NULL,
        :drafted_by_user_id, :drafted_at, :submitted_by_user_id, :submitted_at,
        :approved_by_user_id, :approved_at, :sent_by_user_id, :sent_at,
        :discarded_by_user_id, :discarded_at, :discard_reason,
        CAST(:classification AS classification)
    )
"""

#: Downgrade: the most recent follow-up per meeting back onto the old columns.
_COPY_BACK_LATEST: Final[str] = """
    UPDATE meetings AS m
       SET followup_status = f.status,
           followup_draft = CASE
               WHEN f.body ~ '(?n)^Subject:' THEN f.body
               ELSE 'Subject: ' || f.subject || chr(10) || chr(10) || f.body
           END,
           followup_trace_id = f.trace_id,
           followup_submitted_at = f.submitted_at,
           followup_approved_by_user_id = f.approved_by_user_id,
           followup_approved_at = f.approved_at,
           followup_sent_at = f.sent_at,
           followup_discarded_at = f.discarded_at
      FROM (
          SELECT DISTINCT ON (meeting_id) *
            FROM meeting_followups
           ORDER BY meeting_id, drafted_at DESC, id DESC
      ) AS f
     WHERE f.meeting_id = m.id
"""


def _subject_for(draft: str, title: str) -> str:
    """The first ``Subject:`` line's text, else the meeting title; never longer than 300."""
    match = _SUBJECT_LINE.search(draft)
    subject = match.group("subject").strip() if match else ""
    return (subject or title.strip())[:SUBJECT_MAX]


def _earliest(*moments: datetime | None) -> datetime | None:
    """The earliest of the recorded moments, ignoring the ones that never happened."""
    present = [moment for moment in moments if moment is not None]
    return min(present) if present else None


def _copy_problems(row: Any) -> list[str]:
    """Why ``row`` cannot be copied faithfully, as sentences. Empty when it can."""
    problems: list[str] = []
    status = row.status
    if row.owner_user_id is None:
        problems.append("the meeting has no owner_user_id, so the drafter is unknown")
    if row.followup_draft is None:
        problems.append("the follow-up has a status but no draft text")
    approver = row.followup_approved_by_user_id
    if status in {"APPROVED", "SENT"} and approver is None:
        problems.append(f"it is {status} but names no approver")
    if approver is not None and approver == row.owner_user_id:
        problems.append("its approver is the meeting owner, who is taken as the drafter")
    submitted_at = row.followup_submitted_at
    approved_at = row.followup_approved_at
    sent_at = row.followup_sent_at
    if status in {"DRAFTED", "OFFICER_REVIEW"} and (
        approver is not None or approved_at is not None
    ):
        problems.append(f"it is {status} but carries an approval")
    if status in {"APPROVED", "SENT"} and submitted_at is None:
        problems.append(f"it is {status} but records no submission time")
    if submitted_at is not None and approved_at is not None and submitted_at > approved_at:
        problems.append("its approval time is earlier than its submission time")
    if (status == "SENT") != (sent_at is not None):
        problems.append("its SENT status and its sent timestamp disagree")
    if sent_at is not None and approved_at is None:
        problems.append("it was sent but records no approval time")
    if sent_at is not None and approved_at is not None and approved_at > sent_at:
        problems.append("its sent time is earlier than its approval time")
    if (status == "DISCARDED") != (row.followup_discarded_at is not None):
        problems.append("its DISCARDED status and its discard timestamp disagree")
    return problems


def _copy_followups_out_of_meetings() -> int:
    """Copy every ``meetings.followup_*`` follow-up into ``meeting_followups``.

    Returns the number of rows copied. Validates every row before inserting any, so a
    refusal leaves nothing half-copied (and the migration transaction rolls back anyway).
    """
    bind = op.get_bind()
    rows = list(bind.execute(sa.text(_SELECT_OLD_FOLLOWUPS)))

    refusals = [
        f"meeting {row.meeting_id} ({row.title!r}): {'; '.join(problems)}"
        for row in rows
        if (problems := _copy_problems(row))
    ]
    if refusals:
        msg = (
            "Refusing to migrate meeting follow-ups that cannot be copied without guessing. "
            "Correct these rows (or run the documented demo reset for the synthetic demo "
            "database) and migrate again:\n  " + "\n  ".join(refusals)
        )
        raise RuntimeError(msg)

    insert = sa.text(_INSERT_FOLLOWUP)
    for row in rows:
        owner = row.owner_user_id
        status = row.status
        recipients = [row.organisation_name or MIGRATED_RECIPIENT_FALLBACK]
        submitted_at = row.followup_submitted_at
        sent_at = row.followup_sent_at
        discarded = status == "DISCARDED"
        drafted_at = (
            _earliest(submitted_at, row.followup_approved_at, sent_at, row.followup_discarded_at)
            or row.created_at
        )
        bind.execute(
            insert,
            {
                "id": uuid.UUID(bytes=ULID().bytes),
                "meeting_id": row.meeting_id,
                "status": status,
                "subject": _subject_for(row.followup_draft, row.title),
                "recipients": json.dumps(recipients, ensure_ascii=False),
                "body": row.followup_draft,
                "trace_id": row.followup_trace_id,
                "drafted_by_user_id": owner,
                "drafted_at": drafted_at,
                "submitted_by_user_id": owner if submitted_at is not None else None,
                "submitted_at": submitted_at,
                "approved_by_user_id": row.followup_approved_by_user_id,
                "approved_at": row.followup_approved_at,
                "sent_by_user_id": owner if sent_at is not None else None,
                "sent_at": sent_at,
                "discarded_by_user_id": owner if discarded else None,
                "discarded_at": row.followup_discarded_at,
                "discard_reason": MIGRATED_DISCARD_REASON if discarded else None,
                "classification": row.classification,
            },
        )
    return len(rows)


def upgrade() -> None:
    """Apply this revision."""
    # -- 1. Structured pre-read ----------------------------------------------------
    op.add_column(
        "meetings",
        sa.Column(
            "pre_read_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment=(
                "Structured MEETING_PREP result, validated against MeetingPrepResult before "
                "write. NULL until prepared."
            ),
        ),
    )

    # "Not prepared" is SQL NULL. The column was just added, so on a fresh database this
    # touches nothing; it is here so that re-running the revision over rows written with the
    # JSON literal 'null' (the model before none_as_null=True) leaves them saying IS NULL.
    op.execute(
        "UPDATE meetings SET pre_read_result = NULL WHERE jsonb_typeof(pre_read_result) = 'null'"
    )

    # -- 2. The follow-up table ----------------------------------------------------
    op.create_table(
        TABLE,
        sa.Column(
            "meeting_id",
            sa.UUID(),
            nullable=False,
            comment="Meeting this follows up. RESTRICT: an outbound communication outlives nothing.",
        ),
        sa.Column(
            "status",
            FOLLOWUP_STATUS_TYPE,
            nullable=False,
            comment=(
                "docs/workflows.md section 2 state. By UPDATE, SENT is reachable only from "
                "APPROVED (trigger); the DB cannot tell whether the approver held the permission."
            ),
        ),
        sa.Column(
            "subject",
            sa.String(length=300),
            nullable=False,
            comment="Subject line of the outbound message. Locked outside DRAFTED by trigger.",
        ),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSON array of role/organisation LABELS, never addresses (CHECK forbids '@').",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=False,
            comment="Drafted message text, stored verbatim. Locked outside DRAFTED by trigger.",
        ),
        sa.Column(
            "trace_id",
            sa.UUID(),
            nullable=True,
            comment="ai_traces row that served this draft. NULL means written by hand.",
        ),
        sa.Column(
            "supersedes_followup_id",
            sa.UUID(),
            nullable=True,
            comment="Terminal follow-up this re-draft replaces (workflows rule 0.6). NULL if first.",
        ),
        sa.Column(
            "drafted_by_user_id",
            sa.UUID(),
            nullable=False,
            comment="Drafter. May never be the approver: see ck_..._approver_is_not_drafter.",
        ),
        sa.Column(
            "drafted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the draft was recorded. Provenance: immutable once written.",
        ),
        sa.Column(
            "submitted_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Who submitted the draft for review. Cleared if it returns to DRAFTED.",
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the draft entered OFFICER_REVIEW and its content locked.",
        ),
        sa.Column(
            "approved_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Approver. NULL until approved; never the drafter (CHECK).",
        ),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When approval was granted. Cleared with the approver if approval is revoked.",
        ),
        sa.Column(
            "sent_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Who dispatched it. Dispatch is simulated in the demo; nothing is transmitted.",
        ),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Dispatch time. Non-NULL requires a named approver and approval time (CHECK).",
        ),
        sa.Column(
            "discarded_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Who discarded it. Set only on a DISCARDED row (CHECK).",
        ),
        sa.Column(
            "discarded_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When it was discarded. The row is kept: a discard is never a deletion.",
        ),
        sa.Column(
            "discard_reason",
            sa.String(length=500),
            nullable=True,
            comment="Why it was discarded. Required, non-blank, on a DISCARDED row (CHECK).",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("classification", CLASSIFICATION_TYPE, nullable=False),
        sa.CheckConstraint(
            "sent_at IS NULL OR (approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_meeting_followups_sent_requires_approval"),
        ),
        sa.CheckConstraint(
            "(status = 'SENT') = (sent_at IS NOT NULL)",
            name=op.f("ck_meeting_followups_sent_status_iff_timestamp"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('APPROVED', 'SENT') OR approved_by_user_id IS NOT NULL",
            name=op.f("ck_meeting_followups_approved_states_name_approver"),
        ),
        sa.CheckConstraint(
            "approved_by_user_id IS NULL OR approved_by_user_id <> drafted_by_user_id",
            name=op.f("ck_meeting_followups_approver_is_not_drafter"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('DRAFTED', 'OFFICER_REVIEW') "
            "OR (approved_by_user_id IS NULL AND approved_at IS NULL)",
            name=op.f("ck_meeting_followups_unapproved_states_carry_no_approval"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('APPROVED', 'SENT') OR submitted_at IS NOT NULL",
            name=op.f("ck_meeting_followups_approved_states_were_submitted"),
        ),
        sa.CheckConstraint(
            "approved_at IS NULL OR submitted_at IS NULL OR submitted_at <= approved_at",
            name=op.f("ck_meeting_followups_approval_follows_submission"),
        ),
        sa.CheckConstraint(
            "sent_at IS NULL OR approved_at IS NULL OR approved_at <= sent_at",
            name=op.f("ck_meeting_followups_dispatch_follows_approval"),
        ),
        sa.CheckConstraint(
            "status <> 'DISCARDED' OR (discard_reason IS NOT NULL "
            "AND discard_reason ~ '[^[:space:]]' AND discarded_at IS NOT NULL "
            "AND discarded_by_user_id IS NOT NULL)",
            name=op.f("ck_meeting_followups_discarded_requires_reason"),
        ),
        sa.CheckConstraint(
            "status = 'DISCARDED' OR (discarded_at IS NULL AND discard_reason IS NULL "
            "AND discarded_by_user_id IS NULL)",
            name=op.f("ck_meeting_followups_discard_fields_only_when_discarded"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(recipients) = 'array' AND jsonb_array_length(recipients) "
            "BETWEEN 1 AND 8 AND position('@' in recipients::text) = 0",
            name=op.f("ck_meeting_followups_recipients_are_labels"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_followups_meeting_id_meetings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"], ["ai_traces.id"], name=op.f("fk_meeting_followups_trace_id_ai_traces")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_followup_id"],
            ["meeting_followups.id"],
            name=op.f("fk_meeting_followups_supersedes_followup_id_meeting_followups"),
        ),
        sa.ForeignKeyConstraint(
            ["drafted_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_followups_drafted_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_followups_submitted_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_followups_approved_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_followups_sent_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["discarded_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_followups_discarded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_followups")),
    )
    op.create_index(op.f("ix_meeting_followups_meeting_id"), TABLE, ["meeting_id"], unique=False)
    op.create_index(op.f("ix_meeting_followups_status"), TABLE, ["status"], unique=False)

    # -- 3. At most one live follow-up per meeting ---------------------------------
    op.create_index(
        op.f(LIVE_INDEX),
        TABLE,
        ["meeting_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('DRAFTED', 'OFFICER_REVIEW', 'APPROVED')"),
    )

    # -- 4. Data copy, before the old columns go -----------------------------------
    _copy_followups_out_of_meetings()

    # -- 5. The old follow-up columns ----------------------------------------------
    op.drop_index(op.f("ix_meetings_followup_status"), table_name="meetings")
    op.drop_constraint(
        op.f("ck_meetings_followup_sent_requires_approval"), "meetings", type_="check"
    )
    op.drop_constraint(
        op.f("ck_meetings_followup_sent_status_requires_timestamp"), "meetings", type_="check"
    )
    op.drop_constraint(
        op.f("fk_meetings_followup_approved_by_user_id_users"), "meetings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_meetings_followup_trace_id_ai_traces"), "meetings", type_="foreignkey"
    )
    for column in OLD_COLUMNS:
        op.drop_column("meetings", column)

    # -- 6. Triggers: never deleted, terminal immutable, content locked -------------
    #
    # Same reasoning as the ADR-0004 append-only triggers in the initial schema: a BEFORE
    # trigger binds every client -- the API, the seed, psql -- where an ORM guard binds only
    # the code that remembers it; and RAISE rather than RETURN NULL, because a silently
    # skipped DELETE reports success and changes nothing. TRUNCATE needs its own
    # statement-level trigger: a row-level trigger never fires for TRUNCATE.
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION {REJECT_DELETE_FUNCTION}()
        RETURNS TRIGGER
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION
                'meeting_followups rows are never deleted: discarding a drafted diplomatic communication is itself an audited act (docs/OPEN_QUESTIONS.md Q-05). % is not permitted.',
                TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER {NO_DELETE_TRIGGER} BEFORE DELETE ON {TABLE} "
        f"FOR EACH ROW EXECUTE FUNCTION {REJECT_DELETE_FUNCTION}()"
    )
    op.execute(
        f"CREATE TRIGGER {NO_TRUNCATE_TRIGGER} BEFORE TRUNCATE ON {TABLE} "
        f"FOR EACH STATEMENT EXECUTE FUNCTION {REJECT_DELETE_FUNCTION}()"
    )
    # The UPDATE guard. Order matters only for which sentence the caller reads first:
    # terminal immutability, provenance, the transition pairs, the content lock, and the
    # approval freeze.
    #
    # The pairs are app.domain.enums.FOLLOWUP_TRANSITIONS with the self-transition (edit)
    # left out, because a status that does not change is not a transition here. They are
    # written out rather than generated so the migration stays a fixed record of the DDL it
    # applied; tests/test_schema.py pins the behaviour of every refused shape.
    #
    # The content lock binds every update except DRAFTED to DRAFTED, so the statement that
    # leaves DRAFTED cannot rewrite the text on its way out. The approval freeze lets the
    # approval columns change only when both are set by OFFICER_REVIEW to APPROVED, or both
    # cleared by a return to DRAFTED -- which is what the service's _write_status and
    # _record_approver do, flushed as one UPDATE (the state write runs before the effects,
    # with no query between them). The CHECKs then refuse an approval left on a DRAFTED row.
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION {GUARD_UPDATE_FUNCTION}()
        RETURNS TRIGGER
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.status IN ('SENT', 'DISCARDED') THEN
                RAISE EXCEPTION
                    'meeting_followups row % is % and terminal: a sent or discarded follow-up is immutable (docs/OPEN_QUESTIONS.md Q-05)',
                    OLD.id, OLD.status
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.id IS DISTINCT FROM OLD.id
               OR NEW.meeting_id IS DISTINCT FROM OLD.meeting_id
               OR NEW.drafted_by_user_id IS DISTINCT FROM OLD.drafted_by_user_id
               OR NEW.drafted_at IS DISTINCT FROM OLD.drafted_at
               OR NEW.trace_id IS DISTINCT FROM OLD.trace_id
               OR NEW.supersedes_followup_id IS DISTINCT FROM OLD.supersedes_followup_id THEN
                RAISE EXCEPTION
                    'meeting_followups row %: id, meeting_id, drafted_by_user_id, drafted_at, trace_id and supersedes_followup_id are provenance and never change',
                    OLD.id
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.status IS DISTINCT FROM OLD.status
               AND (CAST(OLD.status AS text), CAST(NEW.status AS text)) NOT IN (
                   ('DRAFTED', 'OFFICER_REVIEW'),
                   ('DRAFTED', 'DISCARDED'),
                   ('OFFICER_REVIEW', 'APPROVED'),
                   ('OFFICER_REVIEW', 'DRAFTED'),
                   ('OFFICER_REVIEW', 'DISCARDED'),
                   ('APPROVED', 'SENT'),
                   ('APPROVED', 'DRAFTED'),
                   ('APPROVED', 'DISCARDED')
               ) THEN
                RAISE EXCEPTION
                    'meeting_followups row %: % to % is not a transition of the follow-up machine (docs/workflows.md section 2); SENT is reached only from APPROVED, and APPROVED only from OFFICER_REVIEW',
                    OLD.id, OLD.status, NEW.status
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF (OLD.status <> 'DRAFTED' OR NEW.status <> 'DRAFTED')
               AND (NEW.subject IS DISTINCT FROM OLD.subject
                    OR NEW.recipients IS DISTINCT FROM OLD.recipients
                    OR NEW.body IS DISTINCT FROM OLD.body) THEN
                RAISE EXCEPTION
                    'meeting_followups row % (% to %): subject, recipients and body are locked outside DRAFTED, including in the statement that leaves DRAFTED, because the artefact an approver sees is the artefact that gets sent',
                    OLD.id, OLD.status, NEW.status
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF (NEW.approved_by_user_id IS DISTINCT FROM OLD.approved_by_user_id
                OR NEW.approved_at IS DISTINCT FROM OLD.approved_at)
               AND NOT (OLD.status = 'OFFICER_REVIEW' AND NEW.status = 'APPROVED'
                        AND NEW.approved_by_user_id IS NOT NULL
                        AND NEW.approved_at IS NOT NULL)
               AND NOT (OLD.status <> 'DRAFTED' AND NEW.status = 'DRAFTED'
                        AND NEW.approved_by_user_id IS NULL
                        AND NEW.approved_at IS NULL) THEN
                RAISE EXCEPTION
                    'meeting_followups row % (% to %): the approval is frozen once given. approved_by_user_id and approved_at are set together only by approval (OFFICER_REVIEW to APPROVED) and cleared together only by a return to DRAFTED',
                    OLD.id, OLD.status, NEW.status
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER {GUARD_UPDATE_TRIGGER} BEFORE UPDATE ON {TABLE} "
        f"FOR EACH ROW EXECUTE FUNCTION {GUARD_UPDATE_FUNCTION}()"
    )

    # -- Privileges ------------------------------------------------------------------
    #
    # The trigger protects against a bug; a missing privilege protects against intent.
    # infra/postgres/init/002_app_role.sql grants naddp_app DELETE on every new table by
    # default, so it is narrowed here. Unlike the append-only tables, UPDATE stays granted:
    # a follow-up legitimately moves through its states. The role check runs in Python for
    # the reason given in the initial schema migration.
    role_exists = bool(
        op.get_bind()
        .execute(sa.text("SELECT 1 FROM pg_roles WHERE rolname = 'naddp_app'"))
        .scalar()
    )
    op.execute(f"REVOKE DELETE, TRUNCATE ON {TABLE} FROM PUBLIC")
    if role_exists:
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON {TABLE} TO naddp_app")
        op.execute(f"REVOKE DELETE, TRUNCATE ON {TABLE} FROM naddp_app")


def downgrade() -> None:
    """Revert this revision. Older follow-ups per meeting are LOST: see the module docstring."""
    # Triggers first: a trigger depends on its function.
    op.execute(f"DROP TRIGGER IF EXISTS {GUARD_UPDATE_TRIGGER} ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS {NO_TRUNCATE_TRIGGER} ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS {NO_DELETE_TRIGGER} ON {TABLE}")
    op.execute(f"DROP FUNCTION IF EXISTS {GUARD_UPDATE_FUNCTION}()")
    op.execute(f"DROP FUNCTION IF EXISTS {REJECT_DELETE_FUNCTION}()")

    # The old columns, exactly as the initial schema declared them.
    op.add_column(
        "meetings",
        sa.Column(
            "followup_status",
            FOLLOWUP_STATUS_TYPE,
            nullable=True,
            comment="NULL means no follow-up drafted yet: a real state, not a missing value.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_draft",
            sa.Text(),
            nullable=True,
            comment="Outbound text under review. Locked for editing once status is OFFICER_REVIEW.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_trace_id",
            sa.UUID(),
            nullable=True,
            comment="ai_traces row behind followup_draft. NULL when the draft was written by hand.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_submitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the draft entered OFFICER_REVIEW and its content locked.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_approved_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Approver. Must not be the drafter; that half is enforced in the service layer.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When approval was granted. Cleared with the approver if approval is revoked.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_sent_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Dispatch time. Non-NULL requires an approver: see this table's CHECK constraints.",
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "followup_discarded_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the draft was abandoned unsent. Mutually exclusive with followup_sent_at.",
        ),
    )
    op.create_foreign_key(
        op.f("fk_meetings_followup_approved_by_user_id_users"),
        "meetings",
        "users",
        ["followup_approved_by_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_meetings_followup_trace_id_ai_traces"),
        "meetings",
        "ai_traces",
        ["followup_trace_id"],
        ["id"],
    )
    op.create_check_constraint(
        op.f("ck_meetings_followup_sent_status_requires_timestamp"),
        "meetings",
        "followup_status <> 'SENT' OR followup_sent_at IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_meetings_followup_sent_requires_approval"),
        "meetings",
        "followup_sent_at IS NULL OR followup_approved_by_user_id IS NOT NULL",
    )
    op.create_index(
        op.f("ix_meetings_followup_status"), "meetings", ["followup_status"], unique=False
    )

    # The most recent follow-up per meeting. Every older one is lost here.
    op.get_bind().execute(sa.text(_COPY_BACK_LATEST))

    # DROP TABLE fires neither DELETE nor TRUNCATE triggers, and those are gone already.
    op.drop_index(op.f(LIVE_INDEX), table_name=TABLE)
    op.drop_index(op.f("ix_meeting_followups_status"), table_name=TABLE)
    op.drop_index(op.f("ix_meeting_followups_meeting_id"), table_name=TABLE)
    op.drop_table(TABLE)

    op.drop_column("meetings", "pre_read_result")
    # The followup_status type is deliberately NOT dropped: the initial schema owns it.
