"""retrieval chunks and knowledge audience window

Revision ID: c5434a714f7a
Revises: a3690c854e4e
Create Date: 2026-09-07 16:05:39.923493+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5434a714f7a"
down_revision: str | None = "a3690c854e4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column(
            "document_id",
            sa.UUID(),
            nullable=True,
            comment="Parent document. Exactly one of this and knowledge_article_id is set.",
        ),
        sa.Column(
            "knowledge_article_id",
            sa.UUID(),
            nullable=True,
            comment="Parent knowledge article. Exactly one parent column is set.",
        ),
        sa.Column(
            "collection",
            sa.Enum("PUBLIC_INTELLIGENCE", "INTERNAL_NOTES", "KNOWLEDGE", name="chunk_collection"),
            nullable=False,
            comment="Logical collection. Every retrieval names the collections it may touch; there is deliberately no 'all collections' value.",
        ),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
            comment="0-based position within the parent. Stable across re-ingestion.",
        ),
        sa.Column(
            "text", sa.Text(), nullable=False, comment="The chunk body, normalised at ingestion."
        ),
        sa.Column(
            "token_estimate",
            sa.Integer(),
            nullable=False,
            comment="Approximate token count, for assembling a context window without re-counting.",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of the normalised text. Ingestion is idempotent on this: an unchanged chunk is not re-embedded, which is what makes re-ingestion cheap.",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.VECTOR(dim=1536),
            nullable=True,
            comment="Chunk vector. NULL until embedded; retrieval skips NULLs rather than erroring.",
        ),
        sa.Column(
            "embedding_model",
            sa.String(length=96),
            nullable=True,
            comment="Which embedder produced the vector. Vectors from different models are not comparable, so a model change must re-embed rather than mix silently.",
        ),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Denormalised citation provenance: source code and name, citation_id, url, version and published date. Copied so a retrieval hit renders without a join.",
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Publication date of the parent, for recency ranking and date filters.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "classification",
            # create_type=False: the `classification` type was created by the initial
            # migration and is shared by every classified table. Autogenerate always
            # re-emits the full CREATE TYPE for a reused enum, which fails with
            # DuplicateObject the moment a second table adopts the mixin.
            postgresql.ENUM(
                "PUBLIC",
                "MISSION_INTERNAL",
                "CONFIDENTIAL",
                "CONSULAR_SENSITIVE",
                name="classification",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(document_id IS NOT NULL)::int + (knowledge_article_id IS NOT NULL)::int = 1",
            name=op.f("ck_document_chunks_exactly_one_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_article_id"],
            ["knowledge_articles.id"],
            name=op.f("fk_document_chunks_knowledge_article_id_knowledge_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="document_ordinal"),
        sa.UniqueConstraint("knowledge_article_id", "ordinal", name="article_ordinal"),
        comment="Retrieval chunks. Classification is denormalised from the parent so the authorisation filter runs in the same WHERE clause as the similarity operator, before ranking.",
    )
    op.create_index(
        op.f("ix_document_chunks_collection"), "document_chunks", ["collection"], unique=False
    )
    op.create_index(
        "ix_document_chunks_collection_classification",
        "document_chunks",
        ["collection", "classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_content_hash"), "document_chunks", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_knowledge_article_id"),
        "document_chunks",
        ["knowledge_article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_published_at"), "document_chunks", ["published_at"], unique=False
    )
    op.create_table_comment(
        "audit_events",
        "APPEND-ONLY (ADR-0004). INSERT and SELECT only; UPDATE and DELETE are refused by the trg_audit_events_append_only and trg_audit_events_no_truncate triggers, and by REVOKE. Corrections are appended, never applied.",
        existing_comment="APPEND-ONLY (ADR-0004). INSERT and SELECT only; UPDATE and DELETE are refused by the trg_audit_events_append_only and trg_audit_events_no_truncate triggers. Corrections are appended, never applied.",
        schema=None,
    )
    # op.create_table() auto-creates the enum types its columns use; op.add_column()
    # does NOT. Without this the ALTER fails with "type knowledge_audience does not exist".
    knowledge_audience = postgresql.ENUM(
        "ALL_STAFF", "TRADE", "CONSULAR", "DIASPORA", "SENIOR", name="knowledge_audience"
    )
    knowledge_audience.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "knowledge_articles",
        sa.Column(
            "audience",
            postgresql.ENUM(
                "ALL_STAFF",
                "TRADE",
                "CONSULAR",
                "DIASPORA",
                "SENIOR",
                name="knowledge_audience",
                create_type=False,
            ),
            nullable=False,
            # server_default backfills the 20 rows that already exist; without it the
            # NOT NULL add fails outright. ALL_STAFF is the correct backfill: an article
            # written before audiences existed was, in fact, written for everyone.
            server_default="ALL_STAFF",
            comment="Who the article was written for. INDEPENDENT of classification, and both filters apply: classification answers 'is this reader cleared', audience answers 'was this written for them'. A trade playbook is not confidential, but serving it as the grounded answer to a consular question is still wrong.",
        ),
    )
    op.add_column(
        "knowledge_articles",
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Start of the validity window. NULL means 'valid since creation'. Retrieval excludes an article that is not yet in force.",
        ),
    )
    op.add_column(
        "knowledge_articles",
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="End of the validity window. NULL means 'no expiry set'. An expired article is excluded from retrieval rather than deleted: it stays readable by direct lookup and keeps prior citations resolvable, but it can never become the source of a NEW grounded answer. Superseded guidance quietly resurfacing is the failure mode this prevents.",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_articles_audience"), "knowledge_articles", ["audience"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_articles_valid_until"),
        "knowledge_articles",
        ["valid_until"],
        unique=False,
    )
    # -- Hand-written indexes (autogenerate cannot express these) ------------------

    # HNSW over cosine distance, matching the operator the retrieval service uses
    # (`<=>`). An index built for a different operator class is simply not used, silently,
    # so the opclass here and the operator in app/services/retrieval.py must agree.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # Full-text half of the hybrid. Expression index on the same to_tsvector() call the
    # query makes; any divergence in the expression or the regconfig means a sequential
    # scan instead of an index scan.
    op.execute(
        "CREATE INDEX ix_document_chunks_fts ON document_chunks "
        "USING gin (to_tsvector('english', text))"
    )

    # Trigram recall for names and short strings the FTS stemmer handles poorly.
    op.execute(
        "CREATE INDEX ix_document_chunks_text_trgm ON document_chunks USING gin (text gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    for index_name in (
        "ix_document_chunks_text_trgm",
        "ix_document_chunks_fts",
        "ix_document_chunks_embedding_hnsw",
    ):
        op.execute(f"DROP INDEX IF EXISTS {index_name}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_articles_valid_until"), table_name="knowledge_articles")
    op.drop_index(op.f("ix_knowledge_articles_audience"), table_name="knowledge_articles")
    op.drop_column("knowledge_articles", "valid_until")
    op.drop_column("knowledge_articles", "valid_from")
    op.drop_column("knowledge_articles", "audience")
    op.execute("DROP TYPE IF EXISTS knowledge_audience")
    op.create_table_comment(
        "audit_events",
        "APPEND-ONLY (ADR-0004). INSERT and SELECT only; UPDATE and DELETE are refused by the trg_audit_events_append_only and trg_audit_events_no_truncate triggers. Corrections are appended, never applied.",
        existing_comment="APPEND-ONLY (ADR-0004). INSERT and SELECT only; UPDATE and DELETE are refused by the trg_audit_events_append_only and trg_audit_events_no_truncate triggers, and by REVOKE. Corrections are appended, never applied.",
        schema=None,
    )
    op.drop_index(op.f("ix_document_chunks_published_at"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_knowledge_article_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_content_hash"), table_name="document_chunks")
    op.drop_index("ix_document_chunks_collection_classification", table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_collection"), table_name="document_chunks")
    op.drop_table("document_chunks")
    # DROP TABLE does not drop the enum type the table declared. Leaving it behind
    # makes downgrade-then-upgrade fail with DuplicateObject, so the round trip is
    # only a true inverse with this line.
    op.execute("DROP TYPE IF EXISTS chunk_collection")
    # ### end Alembic commands ###
